### PR TITLE
Change color scheme

### PR DESCRIPTION
**Pull request by willharren-doosan**
image
Hey Tom, just playing with github so I don't mess something real up at work :) however can I be an admin with my work account, I don't remember the account I used to get in here

### CODE REVIEW

**Comment by harre096** [comment]
You undid the changes it looks like. There is nothing here to merge then right?
You know, you could totally make it prettier and/or change it functionality. Maybe add a randomizer... :)

**Comment by willharren-doosan** [comment]
I changed the color scheme but it looked like I pushed changes onto master, I wanted to create a pull request…ya know do it the right way…so that’s what I was looking at

Cheers!

**Review by willharren-doosan — COMMENTED** [review]
Changed it to a better color scheme than black and orange...YUCK!

**Comment by willharren-doosan** [comment]
Also what's the website to run this again? Your readme looked like it was hosted locally but I could have sworn I ran it on my computer in college ...

**Comment by harre096** [comment]
I merged it without cloning it to check it out locally. Let's see it! You
can run it locally for development and whatever is into master branch gets
published at  https://ytdj.github.io/.
The orange and black is aggressive, but I think it looks better than
windows XP blue in the ocean of black. And the text is low contrast which
makes it hard to read.
You need to download the thing and overhaul the whole theme if you want it
to look nice, I think. :)

**Comment by willharren-doosan** [comment]
Ok, so I didn’t actually know what it was going to look like!! I went through the CSS and replaced orange with something a little more subtle…(like blue!!) Ok ok at least now I know where its at. I haven’t seen this thing for like 3 years give me a break! XD

Thanks!

Will<mailto:McKenzie.Speich@Doosan.com​> Harren
Application Developer Co-op
Doosan Digital Innovation America, LLC
701-241-6373​<mailto:McKenzie.Speich@Doosan.com​>
250 E Beaton Dr
West Fargo, ND 58078

**Pull request merged**
